# Generated by Django 3.0.8 on 2021-07-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_mypost_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
